filter:
    paths: [src/*]
    excluded_paths: [vendor/*, bin/*, spec/*]
tools:
    php_sim:
        min_mass: 25
    php_mess_detector:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true